levels:
  root_dir: "sokoban_core/levels"
  # Folders with .txt: each file may contain one or more levels (separated by an empty line)
  sources:
  - "letslogic"


splits:
  train: "sokoban_core/levels/splits/train.txt"
  val: "sokoban_core/levels/splits/val.txt"
  test: "sokoban_core/levels/splits/test.txt"


filters:
  max_width: 50
  max_height: 50
  min_boxes: 1
  max_boxes: 50